version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
