version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 47000:47000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
